
module TexDSL
	def self.included(receiver)
		Kernel.puts "% this tex file is generated by #{self} at #{Time.now}"
	end

	module_function

	# 
	# Modify method_missing
	# 
	alias_method :original_method_missing, :method_missing

	def method_missing(method, *args, &block)
		if args.length.between?(1, 5)
			make_command(method, args)
		else
			original_method_missing(method, *args, &block)
		end
	end
	
	# 
	# Delete indent on here-document
	# 
	def puts(*strs)
		strs.each do |str|
			Kernel.puts str.to_s.unindent
		end
	end

	String.class_eval do
		def unindent
			gsub(/^#{scan(/^\s*/).min_by{|l|l.length}}/, "")
		end
	end

	# 
	# Make block command
	# 
	def block_command(cmd, args={})
		option = args[:option]
		caption = args[:caption]
		out = "\\begin{#{cmd}}"
		out << "[#{option}]" if option
		out << "{#{caption}}" if caption
		Kernel.puts out
		yield
		Kernel.puts "\\end{#{cmd}}"
	end

	alias_method :start, :block_command
	alias_method :set, :block_command

	# 
	# Make command
	# 
	# note: this method is under method missing
	def make_command(func_name, args)
		args = [args] unless args.respond_to?(:inject)

		out = args.inject("\\#{func_name}") do |memo, arg|
			if arg.kind_of?(Array)
				memo << "[#{arg.join(',')}]"
			elsif arg.kind_of?(String)
				memo << "{#{arg}}"
			end
		end

		Kernel.puts out
	end
end




include(TexDSL)

documentclass %w(a4j titlepage), 'jarticle'
usepackage ['utf8'], 'inputenc'
usepackage 'fancybox, ascmac'
usepackage 'amsmath, amssymb'
usepackage 'fancybox, ascmac'
usepackage ['dvipdfmx'], 'graphicx'
usepackage 'verbatim'
# to display code list
usepackage 'ascmac'
usepackage 'here'
usepackage 'txfonts'
usepackage 'listings, jlisting'
renewcommand '\lstlistingname', 'List'

lstset <<'EOS'
	language = c,
	basicstyle = \ttfamily\small,
	commentstyle = \textit,
	classoffset = 1,
	keywordstyle = \bfseries,
	frame = tRBl,
	framesep = 5pt,
	showstringspaces = false,
	numbers = left,
	stepnumber = 1,
	numberstyle = \footnotesize,
	tabsize = 2
EOS


set :document do
	maketitle ''
	thispagestyle 'empty'
	newpage ''
	setcounter 'page', '1'

	section 'Overview'

	set :screen do
		set :verbatim do
			puts 'write code here'
		end
	end

	set :itembox, caption: 'source code' do
		set :verbatim do
			puts File.open("sample.c", "r", &:read)
		end
	end
end











